### ISSUE TITLE
java.net.SocketException gets thrown

### ISSUE THREAD

**Issue by michaelstalker** [tpope/vim-fireplace#246]
When I run `:Connect` from Vim, I get this message in my REPL:

```
Exception updating the ns-cache #error {
 :cause Socket closed
 :via
 [{:type java.net.SocketException
   :message Socket closed
   :at [java.net.SocketOutputStream socketWrite SocketOutputStream.java 116]}]
 :trace
 [[java.net.SocketOutputStream socketWrite SocketOutputStream.java 116]
  [java.net.SocketOutputStream write SocketOutputStream.java 153]
  [java.io.BufferedOutputStream flushBuffer BufferedOutputStream.java 82]
  [java.io.BufferedOutputStream write BufferedOutputStream.java 126]
  [java.io.FilterOutputStream write FilterOutputStream.java 97]
  [clojure.tools.nrepl.bencode$write_netstring_STAR_ invoke bencode.clj 191]
  [clojure.tools.nrepl.bencode$eval13947$fn__13948 invoke bencode.clj 397]
  [clojure.lang.MultiFn invoke MultiFn.java 233]
  [clojure.tools.nrepl.bencode$eval13947$fn__13948 invoke bencode.clj 398]
  [clojure.lang.MultiFn invoke MultiFn.java 233]
  [clojure.tools.nrepl.bencode$eval13947$fn__13948 invoke bencode.clj 398]
  [clojure.lang.MultiFn invoke MultiFn.java 233]
  [clojure.tools.nrepl.bencode$eval13947$fn__13948 invoke bencode.clj 398]
  [clojure.lang.MultiFn invoke MultiFn.java 233]
  [clojure.tools.nrepl.transport$bencode$fn__14376 invoke transport.clj 103]
  [clojure.tools.nrepl.transport.FnTransport send transport.clj 28]
  [clojure.tools.nrepl.middleware.pr_values$pr_values$fn$reify__14733 send pr_values.clj 27]
  [cider.nrepl.middleware.track_state$update_and_send_cache invoke track_state.clj 170]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$update_in doInvoke core.clj 5923]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.core$apply invoke core.clj 636]
  [clojure.core$binding_conveyor_fn$fn__4444 doInvoke core.clj 1928]
  [clojure.lang.RestFn applyTo RestFn.java 146]
  [clojure.lang.Agent$Action doRun Agent.java 114]
  [clojure.lang.Agent$Action run Agent.java 163]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
```

The message happens as soon as I enter the REPL port, after typing `:Connect`.

I'm using Clojure 1.7.0, Leiningen 2.5.3, and Java 1.8.0_65-b17. I've uninstalled all my Vim plugins except for Fireplace. Do you have any suggestions?

**Comment by michaelstalker** [comment]
The REPL also shows this error when I evaluate some code in Vim with `cpp`. The code gets evaluated correctly, however. For instance typing `cpp` on `(+ 1 1)` results in `2` at the bottom of my Vim window, even though the REPL shows an error.

**Comment by michaelstalker** [comment]
I updated cider-nrepl to 0.9.1, and everything works now. I had been using 0.10.0-SNAPSHOT.

**Comment by michaelstalker** [comment]
@tpope Thanks for all your work on these great Vim plugins!

**Comment by tpope** [comment]
I am actually experiencing this same issue on 0.10.0-SNAPSHOT, though without the stacktrace. It might just be a cider bug but chances are we will have to deal with it eventually.

**Comment by tpope** [comment]
Stack trace makes it clear the problem is the `track-state` middleware, which appears to asynchronously  attempt to send some data *after* the `:status :done` packet has arrived and fireplace has closed the connection. I would say assuming the connection is still open after the requested operation has completed is a bug. @bbatsov what do you think?

**Comment by bbatsov** [comment]
Don't you keep a persistent nREPL connection open? I guess a bit of details about the handling of status `:done` messages by fireplace would be useful. //cc @malabarba

**Comment by Malabarba** [comment]
It should be simple enough to catch the Socket Exception and prevent it from propagating.
Its a harmless exception, so I think it's the easiest solution.

Either that or check whether the connection is still open before sending, but I don't actually know the right way to do that. 😀

**Comment by tpope** [comment]
Due to limitations in Vim itself, Fireplace initiates a new connection for each request, and closes it upon receipt of the `:status :done` packet.

**Comment by Malabarba** [comment]
Just deployed a snapshot that should fix this.

**Comment by glittershark** [comment]
fwiw (idk if this is relevant) this is happening *every time* I run `:Require` in a cljs buffer (not a clj buffer)

My stacktrace:
```
Exception in thread "nREPL-worker-12" java.lang.Error: java.net.SocketException: Socket closed
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at clojure.tools.nrepl.transport$bencode$fn__18833.invoke(transport.clj:103)
        at clojure.tools.nrepl.transport.FnTransport.send(transport.clj:28)
        at cider.nrepl.middleware.track_state$make_transport$reify__34249.send(track_state.clj:184)
        at clojure.tools.nrepl.middleware.pr_values$pr_values$fn$reify__19194.send(pr_values.clj:27)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__19228$fn__19243.invoke(interruptible_eval.clj:122)
        at clojure.main$repl$fn__7417.invoke(main.clj:260)
        at clojure.main$repl.invokeStatic(main.clj:258)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
        at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__19273$fn__19276.invoke(interruptible_eval.clj:222)
        at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__19268.invoke(interruptible_eval.clj:190)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        ... 2 more
```

**Comment by devth** [comment]
Happens all the time for me too 🤔

**Comment by tpope** [comment]
This was resolved when I fixed issues with the socket code on Python 3.
